[build-system]
requires = ["setuptools>=83.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "first-python-notebook"
version = "1.0.0"
description = "A step-by-step guide to analyzing data with Python and the Jupyter notebook."
readme = "README.md"
requires-python = "==3.13.*"
license = "MIT"
dependencies = [
    "jupyterlab",
    "pandas",
    "altair",
    "yolk3k",
    "myst-nb",
    "sphinx-multitoc-numbering",
    "jupyterlite",
    "pyarrow",
    "sphinx",
    "sphinx-autobuild",
    "sphinx-palewire-theme>=0.1.3",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]

[dependency-groups]
dev = [
    "black",
]

[tool.setuptools]
packages = []
