name: Test

on:
  push:
  pull_request:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v7

      - id: install-uv
        name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          version: "0.11.29"
          enable-cache: true
      
      - id: install-python
        name: Install Python
        run: uv python install 3.13
      - id: install-python-dependencies
        name: Install Python dependencies
        run: uv sync --all-groups --locked
        shell: bash

      - id: build-sphinx-documentation
        name: Build Sphinx documentation
        run: make build
        shell: bash

      - id: upload-release-candidate
        name: Upload release candidate
        uses: actions/upload-artifact@v7
        with:
          name: release-candidate
          path: ./docs/_build/
